# Generated by Django 3.1.4 on 2020-12-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ratings_away',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='team',
            name='ratings_home',
            field=models.JSONField(default=dict),
        ),
    ]
