# Generated by Django 3.1.3 on 2020-11-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AddField(
            model_name='team',
            name='_id',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
