# Generated by Django 3.1.4 on 2020-12-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20201212_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ratings_away',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='team',
            name='ratings_home',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
