# Generated by Django 3.1.3 on 2020-11-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20201125_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
