# Generated by Django 3.1.4 on 2020-12-16 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20201213_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('name', models.CharField(max_length=26)),
                ('id', models.CharField(max_length=26, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('name', models.CharField(max_length=26)),
                ('id', models.CharField(max_length=26, primary_key=True, serialize=False)),
                ('conference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.conference')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.conference'),
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.division'),
        ),
    ]
