# Generated by Django 3.1.4 on 2020-12-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20201216_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='calc_rank',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='loses',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='win_pct',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
