# Generated by Django 3.1.4 on 2020-12-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20201210_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ratings_away',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='team',
            name='ratings_home',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
