# Generated by Django 3.1.4 on 2020-12-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20201210_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='away_rating',
        ),
        migrations.RemoveField(
            model_name='team',
            name='home_rating',
        ),
    ]
