# Generated by Django 3.1.4 on 2020-12-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20201217_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
