# Generated by Django 3.1.4 on 2020-12-24 13:44

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_team_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
