# Generated by Django 3.1.4 on 2020-12-24 14:03

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_team_team_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
