# Generated by Django 3.1.4 on 2021-01-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_team_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
