# Generated by Django 3.1.4 on 2021-01-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_auto_20210108_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
