# Generated by Django 3.1.4 on 2021-01-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_team_team_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_id',
        ),
    ]
