# Generated by Django 3.1.4 on 2020-12-12 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('game_data_saved', models.BooleanField(default=False)),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team', to_field='name')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_changes', models.IntegerField()),
                ('teams_string', models.CharField(max_length=50)),
                ('home_points', models.IntegerField()),
                ('away_points', models.IntegerField()),
                ('home_scoring', models.JSONField()),
                ('away_scoring', models.JSONField()),
                ('OT', models.BooleanField(default=False)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('scheduled', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.schedule')),
            ],
        ),
    ]
