# Generated by Django 3.1.3 on 2020-11-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20201125_1446'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='away',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Away', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='home',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Home', to='teams.team'),
        ),
    ]
