# Generated by Django 3.1.3 on 2020-11-25 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20201125_1540'),
        ('schedule', '0002_auto_20201125_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='away',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.team', to_field='name'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='home',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='teams.team', to_field='name'),
        ),
    ]
