# Generated by Django 3.1.3 on 2020-11-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20201125_1540'),
        ('schedule', '0005_auto_20201126_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='teams.team', to_field='name'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='teams.team', to_field='name'),
        ),
    ]
