# Generated by Django 3.1.3 on 2020-11-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20201126_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_changes', models.IntegerField()),
                ('teams_string', models.CharField(max_length=50)),
                ('home_points', models.IntegerField()),
                ('away_points', models.IntegerField()),
                ('home_scoring', models.JSONField()),
                ('away_scoring', models.JSONField()),
                ('OT', models.BooleanField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('scheduled', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.schedule')),
            ],
        ),
    ]
