# Generated by Django 3.1.4 on 2020-12-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_schedule_gamedata_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='gameData_saved',
            new_name='game_data_saved',
        ),
    ]
